=begin comment

LocationIQ

LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.

The version of the OpenAPI document: 1.1.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::Object::Address;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;


use base ("Class::Accessor", "Class::Data::Inheritable");

#
#
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

LocationIQ

LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.

The version of the OpenAPI document: 1.1.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new { 
    my ($class, %args) = @_; 

    my $self = bless {}, $class;

    $self->init(%args);
    
    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }

    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "WWW::OpenAPIClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'Address',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'house_number' => {
        datatype => 'string',
        base_name => 'house_number',
        description => '',
        format => '',
        read_only => '',
            },
    'road' => {
        datatype => 'string',
        base_name => 'road',
        description => '',
        format => '',
        read_only => '',
            },
    'residential' => {
        datatype => 'string',
        base_name => 'residential',
        description => '',
        format => '',
        read_only => '',
            },
    'borough' => {
        datatype => 'string',
        base_name => 'borough',
        description => '',
        format => '',
        read_only => '',
            },
    'neighbourhood' => {
        datatype => 'string',
        base_name => 'neighbourhood',
        description => '',
        format => '',
        read_only => '',
            },
    'quarter' => {
        datatype => 'string',
        base_name => 'quarter',
        description => '',
        format => '',
        read_only => '',
            },
    'hamlet' => {
        datatype => 'string',
        base_name => 'hamlet',
        description => '',
        format => '',
        read_only => '',
            },
    'suburb' => {
        datatype => 'string',
        base_name => 'suburb',
        description => '',
        format => '',
        read_only => '',
            },
    'island' => {
        datatype => 'string',
        base_name => 'island',
        description => '',
        format => '',
        read_only => '',
            },
    'village' => {
        datatype => 'string',
        base_name => 'village',
        description => '',
        format => '',
        read_only => '',
            },
    'town' => {
        datatype => 'string',
        base_name => 'town',
        description => '',
        format => '',
        read_only => '',
            },
    'city' => {
        datatype => 'string',
        base_name => 'city',
        description => '',
        format => '',
        read_only => '',
            },
    'city_district' => {
        datatype => 'string',
        base_name => 'city_district',
        description => '',
        format => '',
        read_only => '',
            },
    'county' => {
        datatype => 'string',
        base_name => 'county',
        description => '',
        format => '',
        read_only => '',
            },
    'state' => {
        datatype => 'string',
        base_name => 'state',
        description => '',
        format => '',
        read_only => '',
            },
    'state_district' => {
        datatype => 'string',
        base_name => 'state_district',
        description => '',
        format => '',
        read_only => '',
            },
    'postcode' => {
        datatype => 'string',
        base_name => 'postcode',
        description => '',
        format => '',
        read_only => '',
            },
    'country' => {
        datatype => 'string',
        base_name => 'country',
        description => '',
        format => '',
        read_only => '',
            },
    'country_code' => {
        datatype => 'string',
        base_name => 'country_code',
        description => '',
        format => '',
        read_only => '',
            },
    'state_code' => {
        datatype => 'string',
        base_name => 'state_code',
        description => '',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'house_number' => 'string',
    'road' => 'string',
    'residential' => 'string',
    'borough' => 'string',
    'neighbourhood' => 'string',
    'quarter' => 'string',
    'hamlet' => 'string',
    'suburb' => 'string',
    'island' => 'string',
    'village' => 'string',
    'town' => 'string',
    'city' => 'string',
    'city_district' => 'string',
    'county' => 'string',
    'state' => 'string',
    'state_district' => 'string',
    'postcode' => 'string',
    'country' => 'string',
    'country_code' => 'string',
    'state_code' => 'string'
} );

__PACKAGE__->attribute_map( {
    'house_number' => 'house_number',
    'road' => 'road',
    'residential' => 'residential',
    'borough' => 'borough',
    'neighbourhood' => 'neighbourhood',
    'quarter' => 'quarter',
    'hamlet' => 'hamlet',
    'suburb' => 'suburb',
    'island' => 'island',
    'village' => 'village',
    'town' => 'town',
    'city' => 'city',
    'city_district' => 'city_district',
    'county' => 'county',
    'state' => 'state',
    'state_district' => 'state_district',
    'postcode' => 'postcode',
    'country' => 'country',
    'country_code' => 'country_code',
    'state_code' => 'state_code'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
